# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/titi7/Desktop/keysights/project_ascon/.Xil/Vivado-14764-PC-TAU/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl 
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    rt::set_parameter singleFileBasedDefaultNettype false
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/ip/clk_wiz_0
    C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/ip/blk_mem_gen_0
    D:/Vivado/2025.1/Vivado/data/rsb/busdef
  } {
      D:/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Vivado/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -sv -include {
    C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/ip/clk_wiz_0
    C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/ip/blk_mem_gen_0
    D:/Vivado/2025.1/Vivado/data/rsb/busdef
  } {
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/ascon_pack.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/Pc.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/Permutation.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/Pl.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/Ps.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/Sbox.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/ascon.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/compteur_double_init.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/fsm_moore.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/new/fsm_top.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/mux_state.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/register_w_en.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/state_register_w_en.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/xor_begin_perm.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/imports/RTL/xor_end_perm.sv
      C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/new/top_ascon.sv
    }
      rt::read_verilog -include {
    C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/ip/clk_wiz_0
    C:/Users/titi7/Desktop/keysights/project_ascon/project_ascon.srcs/sources_1/ip/blk_mem_gen_0
    D:/Vivado/2025.1/Vivado/data/rsb/busdef
  } {
      C:/Users/titi7/Desktop/keysights/project_ascon/.Xil/Vivado-14764-PC-TAU/realtime/clk_wiz_0_stub.v
      C:/Users/titi7/Desktop/keysights/project_ascon/.Xil/Vivado-14764-PC-TAU/realtime/blk_mem_gen_0_stub.v
    }
      rt::read_vhdl -lib xpm D:/Vivado/2025.1/Vivado/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top_ascon
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/titi7/Desktop/keysights/project_ascon/.Xil/Vivado-14764-PC-TAU/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
